### ISSUE TITLE
Wildcard URI Search Strings

### ISSUE THREAD

**Issue by DirectorOsy** [Tymoniden/JiraToolkit#7]
Implement some kind of configureable wildcard search url
e.g. https://myInstance.6x.to/issues/?jql=project%20%3D%20MyProjectKey%20AND%20%22MyCustomField%22%20~%20<MyCustomValue>

Only <MyCustomValue> should be replaced by the wildcard

**Comment by ms-sk** [comment]
Accepted feature request

**Comment by ms-sk** [comment]
Added Queries array to the configuration file. An example Configuration is inside the readme file.

Thanks for your feature request.
