### ISSUE TITLE
AlwaysOnTop Option

### ISSUE THREAD

**Issue by DirectorOsy** [Tymoniden/JiraToolkit#8]
The App should have a mighty always on top option

**Comment by ms-sk** [comment]
Add the possibility to the configuration wether the application should stay on top or not.

If the current implementation is not sufficient, we have to implement the solution here

https://social.msdn.microsoft.com/Forums/vstudio/en-US/697915fe-7cc2-4c6f-8f96-ecc6a4924858/always-on-top-even-in-fullscreengames?forum=wpf
